// user types ////////////////////////////////=>
export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// profile types ///////////////////////////////=>>
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";



// substribe user
export const SUBSCRIBE_USER = "SUBSCRIBE_USER";

// Category types
export const ADD_CATEGORY = "ADD_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";



//  RENTALS TYPES 
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS"; 
export const FETCH_QUESTION_BY_ID_SUCCESS = "FETCH_QUESTION_BY_ID_SUCCESS"; 
export const FETCH_QUESTIONS_INIT = "FETCH_QUESTIONS_INIT"; 
export const FETCH_QUESTIONS_FAIL = "FETCH_QUESTIONS_FAIL"; 

// UPDATE QUESTION TYPES 
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS"; 
export const UPDATE_QUESTION_FAIL = "UPDATE_QUESTION_FAIL"; 
export const RESET_QUESTION_ERRORS = "RESET_QUESTION_ERRORS"; 

